-- SQLITE
CREATE TABLE IF NOT EXISTS BOOKS (ISBN TEXT PRIMARY KEY NOT NULL, TITLE TEXT NULL, AUTHOR TEXT NULL, PUBLISHER TEXT NULL, YEAR TEXT NULL, GENRE TEXT NULL, DESCRIPTION TEXT NULL, MSRP REAL NULL, QUANTITY INTEGER NULL);

DELETE FROM BOOKS WHERE ISBN = 'ISBN';